### ISSUE TITLE
Colaboradores

### ISSUE THREAD

**Issue by italoacasas** [nodejs/iojs-es#115]
Hola a todos, por motivo de un comentario de @stringparser me gustaría saber cuantas personas hay trabajando realmente en el proyecto y cuanto interés existe aun. Creo que con un +1 basta, seguro que muchos ya no están por falta de tiempo etc. Sobre todo la parte de traducción que creo que es la mas afectada.

**Comment by stringparser** [comment]
https://github.com/iojs/iojs-es/commits/master

**Comment by SametSisartenep** [comment]
@italoacasas :+1:

**Comment by ipeluffo** [comment]
Estoy con poco tiempo pero podría seguir colaborando con las revisiones :+1:

**Comment by 007lva** [comment]
Yo ahora estoy copado con otras cosas pero cuando me libere en pocas semanas pienso retomar la traducción

**Comment by paulomcnally** [comment]
+1

**Comment by vrunoa** [comment]
@stringparser @italoacasas este ultimo mes estuve complicadisimo de tiempo cerrando varios proyectos, no pude colaborar como hubiera querido. Este mes puedo ayudar 3 o 4hs semanales. Me fijo en gitter de que manera me puedo poner al día.

**Comment by stringparser** [comment]
@vrunoa perfect. Mañana haré una PR para que hagamos entre todos un documento para que buscar información que actualizar y/o mejorar sea muy simple.

**Comment by vrunoa** [comment]
+1

**Comment by pandres95** [comment]
:+1:

**Comment by stringparser** [comment]
La PR https://github.com/iojs/iojs-es/pull/117 con un borrador para un CONTRIBUTING.md

**Comment by edsadr** [comment]
lo siento mucho chicos... apenas comenzando en NodeSource y he estado es actualizandome de todo lo del trabajo... :( ... obvio que quiero seguir colaborando pero creo que todavia necesito un par de semanas .. sorry @stringparser te he dejado metido ahi :(

**Comment by krosti** [comment]
:+1:

**Comment by eafelix** [comment]
Estoy complicado ahora pero podría seguir colaborando con las revisiones, dentro de poco me libero de unas entregas para volver como siempre
