### ISSUE TITLE
Traductor

### ISSUE THREAD

**Issue by cesarloachamin** [nodejs/iojs-es#122]
Me interesa colaborar en las traducción de los proyectos [Documentación y WebSite], he querido colaborar con el proyecto iojs y me parece un inicio perfecto apoyando en la traducción.

**Comment by stringparser** [comment]
Muy buenas @cesarloachamin. Perfecto. Mira el [CONTRIBUTIN.md](../tree/master/CONTRIBUTING.md) donde puedes ver cómo nos estamos organizando. Cualquier cosa en la que surjan dudas pregunta sin problema. 

Para ver lo que hay pendiente en website y documentación pásate por los siguientes repos: 
- [iojs-es/website](https://github.com/iojs-es/website)
- [iojs-es/io.js](https://github.com/iojs-es/io.js) (Documentación)

Y... ¡bienvenido! :smile:

**Comment by stringparser** [comment]
Cierro este, que ya estas puesto :)
