### ISSUE TITLE
Definir un medio de comunicación

### ISSUE THREAD

**Issue by a0viedo** [nodejs/iojs-es#124]
Dado que al hacer el rename de la organización se perdió el channel de Gitter, esto nos dá una posibilidad de decidir si se quiere continuar utilizándolo o si alguno piensa que podemos optar por otra alternativa.
Si bien es cierto que, desde mi punto de vista, Gitter es de alguna forma más lento que Slack, el mayor limitante para mi es que uno no puede unirse a Gitter sin cuenta de GitHub mientras que en Slack no es necesario.
Mi propuesta es, si es que se llega a un consenso en el uso de Slack, utilizar un grupo dentro del Slack de [LatamJS](https://latamjs.slack.com/messages).

**Comment by edsadr** [comment]
Varios ya estamos en ese slack.. pero voy a decir lo que @stringparser diria :P ... para que chat si nadie entraba? ... la cosa es que hay que volver a echar andar el grupo... ha estado medio muerto desde hace algunos días.

También hay que ver ahora que ya somos de la organización de Node como va a ser el trabajo que van a desempeñar los grupos de i18n ...

**Comment by eafelix** [comment]
@edsadr toda la razón, ademas si armáramos un chat, no corresponderia estar como un canal de y bajo Latam.Js, si no en un slack o chat perteneciente a Node.js project(justamente somos un grupo de trabajo del proyecto y es bajo el donde discutimos los temas). 
Si, como dice @a0viedo estaria bueno crear un canal en Latam.js pero creo que seria mas para compartir contenido y discusiones pero fuera del ambito de los grupos de trabajo del projecto Node.js. 
Que opinan?

**Comment by a0viedo** [comment]
[es]
@edsadr yo no confundiría entre poca actividad y que el grupo haya muerto. Imagino (y me consta para varios integrantes) que las motivaciones iniciales por las cuales decidieron participar no cambiaron. 
En mi caso particular, poseo un número acotado de cantidad de horas que le puedo dedicar a OSS semanalmente. Esto hace que deba elegir constantemente entre muchos proyectos/comunidades.

Así hayan 2 personas activas únicamente, me parece que estaría bien elegir un lugar dónde se pueda mantener una conversación fluída (más dinámica que un GitHub issue).

[en]
At last, as my understanding for what @mikeal said, all the WGs will have the same autonomy as before. We got to decide, as a group, the same decisions that we dealt before.

**Comment by eafelix** [comment]
El punto fuerte con Latam.js es que podemos buscar mas apoyo y gente para el desarrollo del contenido en españo. 
De ultima lo probamos, y si no va, lo mudamos nuevamente.

**Comment by edsadr** [comment]
entiendo @a0viedo ... he tenido un caso similar yo mismo... mi tiempo esta limitado ahora... no me malentiendas, tampoco estoy diciendo que el grupo esta muerto.. lo que queria decir es que la actividad se ha reducido considerablemente...  ahora @eafelix creo que si habria beneficio en buscar quien mas se una al proyecto, esperemos a ver que dice @stringparser tambien, es quien se ha mantenido al frente del cañon

**Comment by eafelix** [comment]
Por supuesto, el ha llevado la posta por el mismo motivo que tenemos todos, no podríamos tomar esta decisión sin el :smile:

**Comment by pandres95** [comment]
Apoyo el uso de Slack.

**Comment by paulomcnally** [comment]
Slack es excelente opción. Tenemos el control, casualmente hice una gema para identificar a quien le toca hacer el café en la oficina. Nosotros podríamos darle muchas más utilidades.

**Comment by ripper2hl** [comment]
Si slack esta bien, pero no tiene un limite ? , recuerdo que en alguna que otra issue se ha mencionado

**Comment by pandres95** [comment]
@ripper2hl en efecto. Sin embargo, lo que se puede hacer con Slackbot es maravilloso.

**Comment by a0viedo** [comment]
@ripper2hl un límite sobre cantidad máxima de usuarios? En LatamJS son 150 personas y por lo que tengo entendido está configurado con la cuenta free. La cuenta free sí tiene un límite sobre historial de mensajes, hasta 10000 mensajes de historial únicamente.

**Comment by sergiolepore** [comment]
@a0viedo hola! El tema de usar el LatamJS es que es...Latam. Alguien, por favor, quiere pensar en España?

![](http://i.ytimg.com/vi/TOlI8diiJq8/hqdefault.jpg)

**Comment by sergiolepore** [comment]
Ahora en serio, es genial el slack de LatamJS, pero cómo haríamos? Un channel extra?

**Comment by a0viedo** [comment]
@sergiolepore no creo que haya problema en recibir integrantes de españa :). mi sugerencia fué porque creo que termina siendo contraproducente crear un slack por cada cosa nueva (o por cada repositorio, organización, etc...si es que comparten objetivos, claro).
un channel un grupo específicos para iojs-es podrían ser

**Comment by sergiolepore** [comment]
@a0viedo de una! +1 al Slack de LatamJS

**Comment by eafelix** [comment]
La pregunta seria, los otros WG, que están usando? 
Podríamos coordinarnos y usar un slack para todo iojs wg 

Por otro lado, LatamJs esta bueno, lo podemos probar y si no va, pensamos otra cosa

**Comment by stringparser** [comment]
Yo voy a venir un poco así

![come on](http://media.aintitcool.com/media/legacy/images2007/simpsonstrailer.jpg)

Y la razón no es por el tiempo que le hecho a esto. Eso es algo que yo he asumido porque creo que lo que se está haciendo nodejs/iojs en general simplemente es increíble. Y no hablo solo de código, si no ejemplo de trabajo, de comprometerse con algo y seguir con ello. De ideales así buenos y humanos. Y sigue pasando en otras areas de la sociedad que "simply we take things for granted". Por eso quiero dar algo sin pedir nada a cambio.

Pero cambio el tono. Que soy incendiario pero a la vez hay que entender la situación personal de cada uno. El tiempo que hay en cada casa, cada cabeza y las prioridades personales de cada uno. Todo es muuuy complicado. 

Mirad, yo en este punto lo que me daría es pena si el trabajo que aquí hay ya hecho y la oportunidad que tenemos todos en participar en algo bueno aunque sea de manera ínfima, simplemente por una cuestión de prioridades. Lo único que hacer es mirar lo que hay pendiente, comunicar con un issue que te vas a poner con eso para que la gente no te pise y hacerlo. 

Que digo yo que si la gente que hizo la www y git no necesitaba más que emails, no creo que haya necesidad de poner capas de tecnología en cada paso. Es como si pagas para ir al gimnasio y luego vas a correr al gimnasio. Salir a correr es gratis y encima entrenas la fuerza de voluntad además de ver el sol y las nubes, etc.

Lo que quiero decir es que, que le añadimos un chat para estar acompañado pues mejor es mejor pero no es necesario. Si se hace, yo estaré ahí. 

Quizás lo que si es necesario es hablar por Hangouts y hacerlo de forma regular, para que la gente se vaya implicando más. Pero hacer otro chat o usar otra herramienta sólo va a cambiar el cómo no el porqué no estamos buscando un rato para echarle al proyecto no creo que sea la solución.

**Comment by ripper2hl** [comment]
@stringparser :+1:

**Comment by edsadr** [comment]
@stringparser ++

**Comment by pandres95** [comment]
@stringparser :+1:

**Comment by edsadr** [comment]
Creo que ya se acordo el medio de comunicación... voy a cerrar esta
