### ISSUE TITLE
GT hangout cada dos semanas

### ISSUE THREAD

**Issue by stringparser** [nodejs/iojs-es#126]
Buenas gente, 

al repositorio le vendría bien que nos uniésemos y volviéramos a dar vida. Más que nada porque sería una lástima que el trabajo ya hecho se vaya deshaciendo poco a poco para desaparecer. Nos hemos juntado bastante gente y por varias razones (algunas que no conozco, otras que si) falta motivación. 

El problema básico que veo es que realmente no nos hemos juntado a hablar de forma continuada y justo esto es lo que vengo a proponer. Que: 

Cada dos semanas, de forma regular se quede un día fijo para hablar de lo que se esté haciendo y lo que se puede mejorar.

Yo propongo los domingos o los viernes a las 20 UTC. En el enlace de abajo podéis ver las zonas horarias de todos los colaboradores. 

http://www.timeanddate.com/worldclock/fixedtime.html?hour=20&min=00&sec=0&sort=1

@nodejs/iojs-es

**Comment by sergiolepore** [comment]
Hola! Reconozco que soy uno de los que desapareció bastante, pero no es por falta de motivación, sino por tiempos algo complejos.
Quiero sumarme al hangout y volver a colaborar como antes. +1.

**Comment by pandres95** [comment]
:+1:

**Comment by ripper2hl** [comment]
Me parece muy bien los domingos :+1:

**Comment by eafelix** [comment]
Domingo +1, disculpen la ausencia, muchas entregas, ojala ya la semana que viene volvemos a la rutina normal.

**Comment by edsadr** [comment]
ok Domingos

**Comment by stringparser** [comment]
De lujo. Seguimos esperando a que más gente confirme. Mientras tanto podemos ir escribiendo de que hablar. 

Todo esto viene en gran parte de haber estado traduciendo [este documento](https://github.com/iojs-es/website/blob/master/content/en/working-groups.md) para el [iojs-es/website](https://github.com/iojs-es/website). En concreto la parte que habla de de las [WG Meetings](https://github.com/iojs-es/website/blob/master/content/en/working-groups.md#wg-meetings). El documento en general es bastante escueto y va al grano en cada apartado. No tiene desperdicio vamos. En el caso de las meetings se dejan muy claras unas pautas para llevarlas a cabo. Esa parte es muy corta, leerla cuando podáis.

**Comment by gollodev** [comment]
Buen día, aparecí por acá, en que se esta colaborando?

**Comment by stringparser** [comment]
Hace unas semanas que está todo un poco parado. Estamos intentando hacer un reset. Ahora mismo quedando en hacer reuniones de forma regular cada dos semanas. Si te viene bien viernes o domingo para hacer un Hangout +1 :)

**Comment by gollodev** [comment]
Domingo +1

**Comment by cesarloachamin** [comment]
Recién me uni al proyecto así que no estoy tan al tanto de todo, de mi parte apoyo cualquier iniciativa para mejorar, :+1: el Domingo

**Comment by stringparser** [comment]
Ok, esta claro que es el Domingo. He dejado un nuevo issue para esto.
