### ISSUE TITLE
GT Hangout Domingo 24.05.2015 a las 20 UTC

### ISSUE THREAD

**Issue by stringparser** [nodejs/iojs-es#127]
> Nota: editar este post y añadir items a la lista libremente. 

Como veníamos hablando en #126 estaría bien hacer un Hangout cada dos semanas siendo esta la primera. 

Hora: [20 UTC](http://www.timeanddate.com/worldclock/fixedtime.html?hour=20&min=00&sec=0&sort=1)
Lugar: your place :smile: 

En el [documento io.js Working Groups](https://github.com/nodejs/website/blob/master/content/en/working-groups.md) (busca la sección wg meetings) se pueden ver unas pautas muy simples de cómo enfocar el hangout. 

La idea es hacer una lista de temas de los que hablar y designar a un moderador. Los temas no tienen porque hablarse completamente, si no lo hacen se mantienen en la lista. 

El moderador lo elegiríamos entre todos. Preferiría no ser yo, de hecho si es alguna persona que lleve poco con nosotros mejor que mejor con la idea de que nos impliquemos. 

A discutir:
* Estado actual de los grupos de trabajo
* Qué hay pendiente en este momento
* Cómo guiar eficientemente a nuevos colaboradores/traductores
* Cómo mantener el proyecto en marcha, sin afectar otras areas de tu vida
* Cómo hacer más visible el contenido que queda pendiente en cada grupo de trabajo
* Definir un medio de comunicación (hablado en #124)
* Designar un moderador para el siguiente Hangout

No seáis tímidos :), criticar todo lo que no os parezca bien de lo que dejo aquí y editar el post.

**Comment by stringparser** [comment]
Gracias @edsadr. Necesitamos un moderador.

Yo propongo a @pandres95 :).

Estamos todos empezando en lo que se refiere a Hangouts, así que sin vergüenza.

**Comment by stringparser** [comment]
Ah, y yo me ocupo de crear el hangout el domingo ;)

**Comment by edsadr** [comment]
roger that

**Comment by stringparser** [comment]
Hangout creado: https://plus.google.com/events/cvbong6qbe3fh5huvgkvggktb4o

He añadido un par de items mas al principio para discutir. Nos vemos luego!

**Comment by stringparser** [comment]
https://plus.google.com/hangouts/_/hoaevent/AP36tYeZxFkhCXYoYXAIHE9YXxwVjqdmwmFoiDvK0Z0DFXPlaF2PEQ

**Comment by stringparser** [comment]
Resumen: 

Asistentes: 
@pandres95, @gollodev, @stringparser

El hangout se a interrumpido por mi parte por problemas de conexión (estais muy lejos xD). Dejo aquí lo que si hemos podido hablar. Si hay algo más dejadlo por aquí.

Resumen de cada uno de los puntos:

* Estado actual de los grupos de trabajo

 Evangelización y Website tienen los contenidos ya traducidos y al día. Falta revisión. Pasar por el repositorio de [evangelism](https://github.com/iojs-es/evangelism/pulls) y dar el +1 o revisar lo que @pandres95 ha traducido ya.

* Qué hay pendiente en este momento

Hacer las PRs del material que está en el repositorio de website para actualizar la web de iojs.
Ver: https://github.com/iojs-es/website/pulls

* Cómo guiar eficientemente a nuevos colaboradores/traductores
Parece que hay información suficiente, vamos a usar Slack (ver #129) ya que @pandres95 ha dicho que el sistema de notificaciones es mejor y eso vendría bien.

* Cómo mantener el proyecto en marcha, sin afectar otras areas de tu vida
No hay una solución clara.

* Cómo hacer más visible el contenido que queda pendiente en cada grupo de trabajo - Pendiente
* Definir un medio de comunicación (hablado en #124) - Probando slack, ver #129 

* Designar un moderador para el siguiente Hangout
Próximo moderador @pandres95 

Fecha para el próximo Hangout es el 07.06.2015

**Comment by edsadr** [comment]
que pena con todos, tuve un inconveniente viajando y apenas llego a tener conexion :(

**Comment by ripper2hl** [comment]
Me equivoque de hora, aquí en México apenas son las 8 en punto xD , disculpen , aun así revisare los puntos
