### ISSUE TITLE
Material, cómo estar al día, enlaces útiles, etc.

### ISSUE THREAD

**Issue by stringparser** [nodejs/iojs-es#3]
Siguiendo al primer comentario de @edsadr en #1. Podríamos discutirlo también en [gitter](https://gitter.im/iojs/iojs-es). Dejaré esto aquí en cualquier caso para que podamos ir añadiendo información.

La traducción de los [api docs](https://github.com/iojs/io.js/tree/v1.x/doc/api) debería ser sencilla, aunque la mayor parte del trabajo irá en la primera tanda de traductores. 

¿Ideas sobre cómo hacerlo?

**Comment by stringparser** [comment]
The Norwegian guys are up already. Today is late but tomorrow I start doing something. 

[https://github.com/iojs/iojs-no](http://www.iojs.no/)

**Comment by stringparser** [comment]
We will have to wait till next week it seems per iojs/website#134, the are preparing material for consistence

To aggregate the important information here: 
* iojs/website#119: WIP - Adds build process (Gulp.js-based) 
* iojs/website#68 - Static Blog page

**Comment by edsadr** [comment]
Bueno chicos despues de discutir mucho con @stringparser , yo tengo la propuesta de que hagamos todos los PR desde un fork unificado en una nueva organización:

https://github.com/iojs-es/website

Envie invitaciones a varios, me cuentan que piensan o propongan otra forma

**Comment by stringparser** [comment]
Hay una etiqueta para los issues que soluciona bastante la vida para estar al día

https://github.com/iojs/website/labels/wg-agenda
