### ISSUE TITLE
¿Hangout?

### ISSUE THREAD

**Issue by stringparser** [nodejs/iojs-es#64]
Estaría bien echar un ratico algún día por hangouts ¿no?

¿Qué horarios tenéis? Porque casi todos estáis en el otro lado del io mundo y mejor me acomodo yo a vosotros. Siempre que no sea muy una locura total... of course :horse_racing:

**Comment by julianduque** [comment]
He creado un Doodle para definamos la fecha, propongo la primera semana de marzo

http://doodle.com/uceb6de9rraa6aa8

En doodle la idea es seleccionar las fechas que mas les gusten y les convengan, creo que las fechas ahí propuestas están en EST / GMT -5 así que deben cuadrar su time zone para poder ajustarlas.

Si no vemos posible los temas horarios podemos volver a proponer otras horas.

**Comment by edsadr** [comment]
+1

**Comment by vrunoa** [comment]
+1

**Comment by stringparser** [comment]
+1

**Comment by eafelix** [comment]
+1

**Comment by julianduque** [comment]
Los que han hecho +1 recuerden poner las fechas disponibles en el Doodle así la podemos planear mas fácil

**Comment by stringparser** [comment]
Hago ping @iojs/iojs-es, para quien falte ;)

**Comment by ipeluffo** [comment]
+1

**Comment by sergiolepore** [comment]
Hola de nuevo! Estuve un poco ocupado desde hace días y tuve que desaparecer. En fin, ahora que estoy disponible y quiero colaborar con el #73 , veo que sigue habiendo un poco de fricción en cuanto a la metodología para mezclar las traducciones o encarar nuevas traducciones.
Tal vez ya lo han discutido, pero es posible acelerar una meeting para cerrar la definición de estos temas? :)

**Comment by italoacasas** [comment]
Realmente han dados alternativas muy buenas, pero aun no se ha decidido una forma de trabajar. Espero que en el Hangout se lleve a un acuerdo, o antes.

**Comment by sergiolepore** [comment]
Ping.

**Comment by a0viedo** [comment]
Dos claras alternativas se desprenden del doodle:
- Martes 3 de Marzo 18hs
- Jueves 5 de Marzo 18hs

**Comment by italoacasas** [comment]
Pienso que necesitamos lo mas pronto posible el Hangout para acabar de definir como se va a trabajar.

**Comment by a0viedo** [comment]
ok acabo de crear el hangouts, debería haberles llegado via email el link para unirse. si a alguien no le llegó, por favor que me avise.

el link para verlo desde youtube lo dejo [acá](http://www.youtube.com/watch?v=BxwZeTNPwkw).

**Comment by eafelix** [comment]
Gracias ale!

**Comment by SametSisartenep** [comment]
@a0viedo Lo veré desde Youtube ;)

**Comment by ipeluffo** [comment]
Gracias! Ya me sumé al Hangout :+1:

**Comment by stringparser** [comment]
Yo también :)

**Comment by vrunoa** [comment]
A mi tambien!

**Comment by ipeluffo** [comment]
Recién me di cuenta de algo importante.

El evento creado por @a0viedo me llegó para las 6 PM de Argentina (GMT-3) en lugar del horario original propuesto por @julianduque de las 6 PM pero GMT-5, es decir, 8 PM de Argentina.

***Por favor, confirmen el horario exacto.***

Ping a todos porque es importante y urgente: @iojs/iojs-es

**Comment by italoacasas** [comment]
Yo también pensé que era GMT -5, confirmen por favor.

**Comment by a0viedo** [comment]
el doodle creo que no tuvo en cuenta esto, o sí? si todos están ok con que sea GMT -5, lo cambio

**Comment by ipeluffo** [comment]
Me da la sensación que "Doodle" no maneja distintas zonas horarias.
Así que @julianduque escribió directamente los horarios considerando GMT-5.

**Comment by italoacasas** [comment]
Si creo todo el mundo puse la disponibilidad pensando en EST / GMT -5

**Comment by a0viedo** [comment]
cambié el horario del hangout, pero no me deja pasarle permisos a otro para inciarlo. yo no voy a poder asistir en ese horario. alguno que pueda crear otro hangouts desde cero con el horario correcto? Para crear el hangout, seguí [este documento](https://github.com/iojs/io.js/wiki/Meetings:-Creating-a-Hangouts-On-Air-Event).

**Comment by stringparser** [comment]
Ok, a mi me viene bien. En España son las doce :dancer:, pero va bien :)

**Comment by edsadr** [comment]
@a0viedo pienso que la idea de usar Doodle era que todos pudieramos cuadrar un horario que pudieramos.. sino puedes en ese... podrias moverlo?

**Comment by italoacasas** [comment]
maybe -1 hora?

**Comment by a0viedo** [comment]
aún así continua siendo el horario dónde hay más coincidencias del equipo. debería hacerse en ese horario

**Comment by italoacasas** [comment]
Bueno maybe puedes escribir tus opiniones sobre los temas, y se tienen en cuenta en el meeting, yo las leo o lo que sea.. A mi opinion eres un miembro importante del proyecto.

**Comment by ipeluffo** [comment]
Dejo esto que encontré recién sobre Doodle que será útil para la próxima reunión:
[How can I schedule an event with people in different time zones?](http://support.doodle.com/customer/portal/articles/645367-how-can-i-schedule-an-event-with-people-in-different-time-zones-)

**Comment by stringparser** [comment]
Lo mejor sería quedar día fijo a cada dos semanas o mes y que que se confirme asistencia. La semana en la que se realice el hangout para crearlo o aplazarlo a la siguiente fecha.

**Comment by italoacasas** [comment]
Realmente creo que con 1 meeting general con todos los WG, al mes es
suficiente, y ya cada WG pueden organizar los que crean correspondientes
pero seria decisión de cada WG

**Comment by stringparser** [comment]
De acuerdo. ¿Qué os parece el primer Lunes de cada mes para las reuniones con todos los WG?

**Comment by stringparser** [comment]
@iojs/iojs-es ¿hacemos un Hangout para ver la gente que quiere seguir colaborando?

**Comment by pandres95** [comment]
@stringparser :+1:

**Comment by edsadr** [comment]
bueno.. vuelvo a participar activamente... para cuando sería el hangout?

**Comment by stringparser** [comment]
Vamos a poner una fecha. ¿Qué os parece este domingo? Si no, proponed otro día.

**Comment by edsadr** [comment]
Puedo hasta este miercoles y ya puedo el lunes entrante ... salgo de viaje miercoles en la noche

**Comment by eafelix** [comment]
mañana les gustaría?

**Comment by stringparser** [comment]
Ok, lo que digáis me apunto cuando podais ;)

**Comment by stringparser** [comment]
http://doodle.com/u9p992eu4yqb9yqf

**Comment by stringparser** [comment]
Espera, yo mañana no puedo. ¿A las 20 UTC el miércoles estaría bien o es muy temprano por allí? 

[Your time (Wolfram)](http://www.wolframalpha.com/input/?i=20%3A00+UTC)
[Country times (timeanddate.com)](http://www.timeanddate.com/worldclock/fixedtime.html?hour=20&min=00&sec=0&sort=1)

**Comment by edsadr** [comment]
Mañana a esa hora esta bien y me puedo quedar 1 hora

**Comment by stringparser** [comment]
Pero yo mañana no puedo. A ver si se apunta alguien más y lo hacemos la semana que viene que tu puedes parece todos los días.

**Comment by edsadr** [comment]
+1

**Comment by pandres95** [comment]
Ya están mis datos, por mi parte, un :+1: para Hangout :D

**Comment by stringparser** [comment]
Qué os parece fijar el día al Lunes 4 y la hora a las [20 UTC](http://www.timeanddate.com/worldclock/fixedtime.html?hour=20&min=00&sec=0&sort=1). 

Si no proponer ;)

**Comment by stringparser** [comment]
En [esta tabla](http://www.timeanddate.com/worldclock/meetingtime.html?iso=20150504&p1=141&p2=51&p3=485&p4=433&p5=150&p6=1079&p7=131&p8=156&p9=41) se ven bastante mejor las zonas horarias de todos los colaboradores.

**Comment by eafelix** [comment]
Semana que viene va a venir mucho mejor me parece no ?

**Comment by stringparser** [comment]
Eso estamos hablando (la del 4 al 8 de Mayo), ¿o te refieres a otra?

**Comment by stringparser** [comment]
@iojs/iojs-es, entonces ¿hay hangout esta semana o no? Dejo el link de los horarios que puse en gitter. 

[Zonas horarias de la quedada](http://www.timeanddate.com/worldclock/meetingtime.html?iso=20150504&p1=141&p2=51&p3=485&p4=433&p5=150&p6=1079&p7=131&p8=156&p9=41)

**Comment by pandres95** [comment]
Me parece que a las 20:00 UTC está bien para todos. Ahora bien, yo puedo hoy, ¿quienes más pueden darse ese pequeño lujo? :+1:

**Comment by edsadr** [comment]
entonces ? hoy a las 20 UTC?

**Comment by pandres95** [comment]
¡Si, que sea hoy a las 20 UTC!

**Comment by edsadr** [comment]
por lo que veo solo hemos aplicado en el doodel @pandres95 @stringparser y yo

**Comment by stringparser** [comment]
ok, yo estaré por casa nos vemos en gitter primero y nos pasamos el link del hangout

**Comment by edsadr** [comment]
me gustaria saber sobre @eafelix quien comento recientemente en este issue su interes por asistir ... ya que somos bien pocos por que no lo esperamos?

**Comment by stringparser** [comment]
si, perfecto, deacuerdo

**Comment by stringparser** [comment]
ok, esto no está funcionado como sería de esperar, propongo #126
